language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: BS+HkaAAf6wSdsV9pBVQgD/cr7sZRMLK+AnYg5r/wWG8sVgTC5eKDdhCaKaWQ/TA6QP4v0WxWLeij3Avo2RQemNaytd7oOKUB5+keyFfMlxgCv2F0NlrQ+0HgQEdN2M1TiG0O7DOhtdBkpk4WCCWwgSP5vBcrp9w1EzkZoH/dOE=
  file:
    - "strip-markdown.js"
    - "strip-markdown.min.js"
  on:
    tags: true
