language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: aljGeSHmOn4ycz4O4/VGdP+96PNJwUEA7YFDxt9ToUpD6NvvirxJOFWntMpikelwXP3+c6+DIy7RhJgemuniv+Gq9NplNNQV4JF1hwBuEGjg4VSglRBpaP5EeqeWRkrfu5M59X7eywhbvKDJxqWjuY6vkHEXP28/tH/0S6kEujA=
  file:
    - "strip-markdown.js"
    - "strip-markdown.min.js"
  on:
    tags: true
